defaults:
- scope:
    path: ""
  values:
    lang: "en"
    date_fmt: "%B %d, %Y"

- scope:
    path: ""
    type: "pages"
  values:
    layout: "default"

- scope:
    path: ""
    type: "posts"
  values:
    layout:     "post"
    date_fmt:   "%F"
    categories: "news"
    comments:   false

exclude:
- assets/css/style.css
- Gemfile
- Gemfile.lock
- LICENSE
- new_post.sh
- node_modules
- package.json
- package-lock.json
- Rakefile
- README.md
- setup.sh
- TODO.md
- yarn.lock
- yarn-error.log

plugins:
- jekyll-sitemap
- jemoji

name: "AZDrums"
url: "https://azdrums.github.io"
description: "E-Drums Projects"

repository:
  id:     "azdrums"
  branch: "master"

locale:
  default: "en"

authors:
  content: "redtide"
  web:     "redtide"

#google:
#  analytics: "UA-115525913-1"
#  cse: "006405061798903882253:eeqyvtqcspo"

realfavicons:
  sizes:
    big:    "152x152"
    medium: "32x32"
    small:  "16x16"
  colors:
    mask:    "#5bbad5"
    ms_tile: "#2d89ef"
    theme:   "#ffffff"
