defaults:
- scope:
    path: ""
  values:
    lang: "en"

- scope:
    path: ""
    type: "pages"
  values:
    layout: "default"

- scope:
    path: ""
    type: "posts"
  values:
    layout:     "post"
    date_fmt:   "%F"
    categories: "news"
    comments:   false

exclude:
- assets/css/style.css
- Gemfile
- Gemfile.lock
- LICENSE
- new_post.sh
- node_modules
- package.json
- package-lock.json
- Rakefile
- README.md
- setup.sh
- TODO.md
- yarn.lock
- yarn-error.log

plugins:
- jekyll-sitemap

name: "AZDrums"
url: "https://azdrums.github.io"
description: "E-Drums Projects"

repository:
  name: "master"
  url: "https://github.com/azdrums/azdrums.github.io"

locale:
  default: "en"

authors:
  content: "RedTide"
  web:     "RedTide"

search: "google-cse.js"

google:
  analytics_code: "UA-115525913-1"
  cse_code: "006405061798903882253:eeqyvtqcspo"
